baseURL = "https://blog.ygxb.net/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "YGXB_net 的博客"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"


[params]
# DoIt 主题版本
version = "0.4.X"
# 网站名称
title = "YGXB_net 的博客"
# 网站描述
description = "这是一个我的个人博客网站"
# 网站关键词
keywords = ["YGXB_net", "博客", "Blog", "Theme", "Hugo"]
#  网站默认主题样式 ("light", "dark", "black", "auto")
defaultTheme = "auto"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["https://img.ygxb.net/i/2023/08/25/64e8bc4fcc148.jpg"]
#  版权信息
license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议</a>进行许可。'

# 不蒜子计数
[params.ibruce]
enable = true

#  搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ("algolia", "fuse")
type = "fuse"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false

# 页面底部信息配置
[params.footer]
enable = true
#  自定义内容 (支持 HTML 格式)
custom = ''
#  是否显示 Hugo 和主题信息
hugo = true
#  托管服务信息 (支持 HTML 格式)
# <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
hostedOn = ''
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2023
# ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="知识共享许可协议" style="border-width:0;display:inline;" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议</a>进行许可。'

# 主页配置
[params.home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱, 用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
# 将你的头像文件放置于 static 或者 assets 目录下
# 文件路径是相对于 static 或者 assets 目录的
avatarURL = "https://img.ygxb.net/i/2023/08/25/64e8bc4fcc148.jpg"
# 头像的链接指向的 URL
avatarLinkURL = ""
#  主页显示的网站标题 (支持 HTML 格式)
title = "YGXB_net"
# 主页显示的网站副标题
subtitle = "Hi 这是一个我的个人博客网站"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明 (支持 HTML 格式)
disclaimer = ""

# 作者的社交信息设置
[params.social]
GitHub = "ygxbnet"
QQ = "3040809965"
QQGroup = ""
Email = "me@ygxb.net"
RSS = true

#  文章页面配置
[params.page]
# 是否使用 lightgallery
lightgallery = true
#  文章页面的分享信息设置
[params.page.share]
enable = true
Twitter = true
Facebook = true
# Linkedin = false
# Whatsapp = true
# Pinterest = false
# Tumblr = false
# HackerNews = false
Reddit = true
# VK = false
# Buffer = false
# Xing = false
# Line = true
# Instapaper = false
# Pocket = false
# Digg = false
# Stumbleupon = false
# Flipboard = false
Weibo = true
# Renren = false
# Myspace = true
# Blogger = true
Baidu = true
# Odnoklassniki = false
Evernote = true
# Skype = false
# Trello = false
# Mix = false
Mastodon = true

# 评论系统设置
[params.page.comment]
enable = true
# Artalk 评论系统设置
[params.page.comment.artalk]
enable = true
server = "https://artalk.ygxb.net"
site = "我的博客"
lite = false
katex = false
lightbox = true
pageview = true
commentCount = true


[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
weight = 2

[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
weight = 3


# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false


# 作者配置
[author]
name = "YGXB_net"
email = "me@ygxb.net"
link = ""
avatar = ""
gravatarEmail = "ygxb-net@outlook.com"


# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5


# 用于 Hugo 输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON"]
